### ISSUE TITLE
Making it throw friendly

### ISSUE THREAD

**Issue by thetutlage** [substack/node-syntax-error#11]
It works great, but when i throw error returned by syntax-error then stack trace seems to be incomplete.

**Comment by zertosh** [comment]
Can you give me an example?

**Comment by thetutlage** [comment]
Why not , clone this [repo](https://github.com/thetutlage/syntax-error-example) and run `index.js`. You will get an idea what i mean

**Comment by zertosh** [comment]
Thanks for the repo. I think it's just as simple as adding `Error.captureStackTrace(this, module.exports);` below `SyntaxError.call(this);` - is the result after that what you expect?

**Comment by thetutlage** [comment]
Didn't get where is `SyntaxError.call(this);`

**Comment by thetutlage** [comment]
Ohh got it you are talking on `syntax-error` but results are different it has reference to the file from where `check` method is called not the file which has syntax error

**Comment by zertosh** [comment]
So I put #12 together, but I'm a little iffy about it because the stack is from the [`eval`](https://github.com/substack/node-syntax-error/blob/a0aa102490a79ad9d38b4d5f43c4c2d6410598f1/index.js#L8) - so it doesn't include the original file. Since the code doesn't actually run, you'd have to construct your own stack trace.

**Comment by thetutlage** [comment]
Okay make sense, i did it in a funny way and was hoping for a better solution. Check out the repo i updated just now

**Comment by zertosh** [comment]
I'd be totally cool with something like that if I had some reasonable certainty of the structure of the stack trace. It seems like it's an interpreter specific thing https://chromium.googlesource.com/v8/v8/+/master/docs/javascript_stack_trace_api.md

**Comment by thetutlage** [comment]
Yes it is , but i think you should not include it as it is kind of dirty hack , so the one consuming your module can make a decision on how to build stack
