### ISSUE TITLE
Add allowHashBang option?

### ISSUE THREAD

**Issue by chemzqm** [substack/node-syntax-error#13]
acorn has allowHashBang option, why we can't?
This could be useful for the javascript file with shabang

**Comment by mattdesl** [comment]
@zertosh This would be handy, this issue is currently leading to confusing errors. 

<img width="891" alt="screen shot 2016-01-27 at 10 20 21 am" src="https://cloud.githubusercontent.com/assets/1383811/12617898/980025f2-c4df-11e5-8b4a-990b88f3e2c1.png">
